# Generated by Django 3.1.1 on 2020-09-13 09:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
