# Generated by Django 3.1.1 on 2020-09-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20200913_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_follower',
            new_name='user_follow',
        ),
    ]
