# Generated by Django 3.1.1 on 2020-09-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20200914_1133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'user_follow')},
        ),
    ]
